apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: taskflow

data:
  PORT: "5003"
  NODE_ENV: "development"
  JWT_EXPIRES_IN: "1d"
  BCRYPT_SALT_ROUNDS: "10"
  DATABASE_URL: "postgresql://postgres:postgres@postgres-service:5432/auth_db"