apiVersion: v1
kind: Service
metadata:
  name: email-service
  namespace: taskflow
  labels:
    app: email-service
spec:
  type: ClusterIP
  selector:
    app: email-service
  ports:
    - name: http
      port: 5006
      targetPort: 5006
