apiVersion: v1
kind: ConfigMap
metadata:
  name: task-service-config
  namespace: taskflow

data:
  PORT: "5004"
  NODE_ENV: "development"

  DATABASE_URL: "postgresql://postgres:postgres@postgres-service:5432/tasks_db"

  KAFKA_BROKER: "kafka:9092"
  KAFKA_CLIENT_ID: "task-service"