apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
  namespace: taskflow

spec:
  replicas: 1

  selector:
    matchLabels:
      app: task-service

  template:
    metadata:
      labels:
        app: task-service

    spec:
      containers:
        - name: task-service
          image: pnajan/taskflow-task-service:v1

          ports:
            - containerPort: 5004

          envFrom:
            - configMapRef:
                name: task-service-config

            - secretRef:
                name: task-service-secret