services:
  frontend:
    build: .
    container_name: taskflow-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - backend-network

networks:
  backend-network:
    external: true
    name: task-app_backend-network
